name = "bober"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a73b28fd8059d171c4c72ff1909f592285bf99f6fa7a228b743972d353c0351c"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
