name = "bober"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5df5e3a162cb410ae67cd1a430ad813c10e1606e092c84cb374a680467b1ba2"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
