name = "bober"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438916da2113a3aa11ef7cb6d321d702a933d636b0679ad5755494886fb8cae3"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
