name = "bober"
author = "goger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "806c59bc903e60d79d245fd606c81b6ef1486534190a90b31fd155cd66f13dae"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
