name = "bober"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b1bec6f018a1a9e0cef581295384e39e09c610c51eef64c48f2719b7d39e7cb"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
