name = "bober"
author = "goger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8bcbbc55388a01502609316f8f8dc02c90fe5c3447bf1cfcf2bbd48a8434f7e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
